version: "3.8"
version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      args:
        # falls du im Code dennoch ENV nutzt, sonst entfällt
        REACT_APP_API_URL: http://backend:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
