version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:

    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
